layout:
  qmk_keyboard: corne_rotated
  layout_name: LAYOUT_split_3x5_3
layers:
  Left-Thumb Combos:
    - ["|", ")", "}", "]", null, null, null, 9, null, null]
    - ["!", "(", "{", "[", null, null, 3, 1, 5, 7]
    - ["~", null, null, null, null, null, null, null, null, null]
    - null
    - {type: held}
    - null
    - null
    - null
    - null
  Right-Thumb Combos:
    - [null, null, 8, null, null, null, "\\", "%", "^", "`"]
    - [6, 4, 0, 2, null, null, "*", "#", "$", "&"]
    - [null, null, null, null, null, null, null, null, null, null]
    - null
    - null
    - null
    - null
    - {type: held}
    - null
