layout:
  qmk_keyboard: corne_rotated
  layout_name: LAYOUT_split_3x5_3
layers:
  DEF:
    - [F, P, D, L, X, ;, U, O, Y, B]
    - [{h: Gui, t: S}, {h: Alt, t: N}, {h: Ctrl, t: T}, {h: Shift, t: H}, K, ",", {h: Shift, t: A}, {h: Ctrl, t: E}, {h: Alt, t: I}, {h: Gui, t: "C"}]
    - [V, W, G, M, J, "-", ".", "'", "=", "/"]
    - {h: Gui,   t: Tab}
    - {h: NAV,  t: R}
    - {h: NUM,  t: NUMWORD}
    - Enter
    - {h: SYM, t: Space}
    - Backspace
  NUM:
    - [null, null, 8, null, X, ";", null, 9, null, null,]
    - [6, 4, 0, 2, K, ",", 3, 1, 5, 7,]
    - [null, W, Shift G, null, J, "-", ".", "'", "=", "/"]
    - null
    - null
    - {type: held}
    - Enter
    - Space
    - Backspace
  NAV:
    - [null, null, null, null, null, Home, Page Down, Page Up, End, null]
    - [Gui, Alt, Ctrl, Shift, null, Left, Down, Up, Right, null]
    - [null, null, null, null, null, null, ".", null, null, null]
    - null
    - {type: held}
    - null
    - null
    - FUN
    - null
  SYM:
    - ["~", ")", "}", "]", null, null, "\\", "%", "^", "`"]
    - ["|", "(", "{", "[", null, null, "*", "#", "$", "&"]
    - [null, null, null, null, null, null, null, null, null, null]
    - null
    - null
    - null
    - null
    - {type: held}
    - null
  FUN:
    - [null, null, F8, null, null, Play Pause, Media Prev, F9, Media Next, null]
    - [F6, F4, F10, F2, F12, F11, F3, F1, F5, F7]
    - [null, null, null, null, null, null, Vol Down, Vol Up, Vol Mute, null]
    - null
    - {type: held}
    - null
    - null
    - {type: held}
    - null
